# Sponsorship channels for Immanueal1 open-source hardware & firmware development

github: Immanueal1
ko_fi: krishnakantgarhe
custom: ["https://www.linkedin.com/in/krishna-kant-garhe-immanueal-etc-engineer/"]
